"""Add cloth, outfit, and wardrobe tables

Revision ID: 3ce69cf090dd
Revises: 0007_drop_user_currency
Create Date: 2026-06-30 22:29:05.092951
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ce69cf090dd'
down_revision = '0007_drop_user_currency'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clothing_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_clothing_items_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clothing_items'))
    )
    op.create_index(op.f('ix_clothing_items_user_id'), 'clothing_items', ['user_id'], unique=False)
    op.create_table('outfits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_outfits_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outfits'))
    )
    op.create_index(op.f('ix_outfits_user_id'), 'outfits', ['user_id'], unique=False)
    op.create_table('wardrobes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_wardrobes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wardrobes'))
    )
    op.create_index(op.f('ix_wardrobes_user_id'), 'wardrobes', ['user_id'], unique=False)
    op.create_table('calendar_outfits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('outfit_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits.id'], name=op.f('fk_calendar_outfits_outfit_id_outfits'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_calendar_outfits_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calendar_outfits'))
    )
    op.create_index(op.f('ix_calendar_outfits_outfit_id'), 'calendar_outfits', ['outfit_id'], unique=False)
    op.create_index(op.f('ix_calendar_outfits_user_id'), 'calendar_outfits', ['user_id'], unique=False)
    op.create_table('clothing_item_wardrobes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('clothing_item_id', sa.String(length=36), nullable=False),
    sa.Column('wardrobe_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['clothing_item_id'], ['clothing_items.id'], name=op.f('fk_clothing_item_wardrobes_clothing_item_id_clothing_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wardrobe_id'], ['wardrobes.id'], name=op.f('fk_clothing_item_wardrobes_wardrobe_id_wardrobes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clothing_item_wardrobes'))
    )
    op.create_index(op.f('ix_clothing_item_wardrobes_clothing_item_id'), 'clothing_item_wardrobes', ['clothing_item_id'], unique=False)
    op.create_index(op.f('ix_clothing_item_wardrobes_wardrobe_id'), 'clothing_item_wardrobes', ['wardrobe_id'], unique=False)
    op.create_table('outfit_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('outfit_id', sa.String(length=36), nullable=False),
    sa.Column('clothing_item_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['clothing_item_id'], ['clothing_items.id'], name=op.f('fk_outfit_items_clothing_item_id_clothing_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits.id'], name=op.f('fk_outfit_items_outfit_id_outfits'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outfit_items'))
    )
    op.create_index(op.f('ix_outfit_items_clothing_item_id'), 'outfit_items', ['clothing_item_id'], unique=False)
    op.create_index(op.f('ix_outfit_items_outfit_id'), 'outfit_items', ['outfit_id'], unique=False)
    op.create_table('outfit_wardrobes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('outfit_id', sa.String(length=36), nullable=False),
    sa.Column('wardrobe_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits.id'], name=op.f('fk_outfit_wardrobes_outfit_id_outfits'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wardrobe_id'], ['wardrobes.id'], name=op.f('fk_outfit_wardrobes_wardrobe_id_wardrobes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outfit_wardrobes'))
    )
    op.create_index(op.f('ix_outfit_wardrobes_outfit_id'), 'outfit_wardrobes', ['outfit_id'], unique=False)
    op.create_index(op.f('ix_outfit_wardrobes_wardrobe_id'), 'outfit_wardrobes', ['wardrobe_id'], unique=False)
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_supabase_user_id'), type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_supabase_user_id'), ['supabase_user_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_outfit_wardrobes_wardrobe_id'), table_name='outfit_wardrobes')
    op.drop_index(op.f('ix_outfit_wardrobes_outfit_id'), table_name='outfit_wardrobes')
    op.drop_table('outfit_wardrobes')
    op.drop_index(op.f('ix_outfit_items_outfit_id'), table_name='outfit_items')
    op.drop_index(op.f('ix_outfit_items_clothing_item_id'), table_name='outfit_items')
    op.drop_table('outfit_items')
    op.drop_index(op.f('ix_clothing_item_wardrobes_wardrobe_id'), table_name='clothing_item_wardrobes')
    op.drop_index(op.f('ix_clothing_item_wardrobes_clothing_item_id'), table_name='clothing_item_wardrobes')
    op.drop_table('clothing_item_wardrobes')
    op.drop_index(op.f('ix_calendar_outfits_user_id'), table_name='calendar_outfits')
    op.drop_index(op.f('ix_calendar_outfits_outfit_id'), table_name='calendar_outfits')
    op.drop_table('calendar_outfits')
    op.drop_index(op.f('ix_wardrobes_user_id'), table_name='wardrobes')
    op.drop_table('wardrobes')
    op.drop_index(op.f('ix_outfits_user_id'), table_name='outfits')
    op.drop_table('outfits')
    op.drop_index(op.f('ix_clothing_items_user_id'), table_name='clothing_items')
    op.drop_table('clothing_items')
    # ### end Alembic commands ###
