"""add_unique_constraint_to_calendar_outfit

Revision ID: 46139ad10209
Revises: 6885634e8098
Create Date: 2026-07-08 11:44:25.729846
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46139ad10209'
down_revision = '6885634e8098'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_calendar_outfit_date', 'calendar_outfits', ['outfit_id', 'date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_calendar_outfit_date', 'calendar_outfits', type_='unique')
    # ### end Alembic commands ###
