"""Add image_url to outfits

Revision ID: 6274d3b2f48a
Revises: d4b660ff9871
Create Date: 2026-07-05 14:30:48.240893
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6274d3b2f48a'
down_revision = 'd4b660ff9871'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outfits', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outfits', 'image_url')
    # ### end Alembic commands ###
