"""add push notification fields

Revision ID: 96f5a077648e
Revises: c3d4e5f6a7b8
Create Date: 2026-07-13 00:23:05.883036
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96f5a077648e'
down_revision = 'c3d4e5f6a7b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('push_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('daily_reminders', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'daily_reminders')
    op.drop_column('users', 'push_token')
    # ### end Alembic commands ###
