"""add image_url to wardrobes

Revision ID: d4b660ff9871
Revises: 3ce69cf090dd
Create Date: 2026-07-02 16:45:43.904755
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4b660ff9871'
down_revision = '3ce69cf090dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wardrobes', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wardrobes', 'image_url')
    # ### end Alembic commands ###
