"""add_notification_toggles

Revision ID: d63f860f2238
Revises: 96f5a077648e
Create Date: 2026-07-19 17:19:16.215720
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd63f860f2238'
down_revision = '96f5a077648e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_style_tips_user_id'), 'style_tips', type_='unique')
    op.drop_index(op.f('ix_style_tips_user_id'), table_name='style_tips')
    op.create_index(op.f('ix_style_tips_user_id'), 'style_tips', ['user_id'], unique=True)
    op.add_column('users', sa.Column('fit_pic_reminders', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('weekly_stats_reminders', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'weekly_stats_reminders')
    op.drop_column('users', 'fit_pic_reminders')
    op.drop_index(op.f('ix_style_tips_user_id'), table_name='style_tips')
    op.create_index(op.f('ix_style_tips_user_id'), 'style_tips', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('uq_style_tips_user_id'), 'style_tips', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
