"""add outfit_images table

Revision ID: dde67129cdfa
Revises: e5c7811ff083
Create Date: 2026-07-06 21:07:05.888121
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dde67129cdfa'
down_revision = 'e5c7811ff083'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outfit_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('outfit_id', sa.String(length=36), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits.id'], name=op.f('fk_outfit_images_outfit_id_outfits'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outfit_images'))
    )
    op.create_index(op.f('ix_outfit_images_date'), 'outfit_images', ['date'], unique=False)
    op.create_index(op.f('ix_outfit_images_outfit_id'), 'outfit_images', ['outfit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outfit_images_outfit_id'), table_name='outfit_images')
    op.drop_index(op.f('ix_outfit_images_date'), table_name='outfit_images')
    op.drop_table('outfit_images')
    # ### end Alembic commands ###
